### ISSUE TITLE
Host on GitHub Pages

### ISSUE THREAD

**Issue by AV306** [GoulartNogueira/BadUI#1]
Could you host this live on GitHub pages? This way we can view it anywhere and on mobile :D

**Comment by imansour12** [comment]
yeah agreed

**Comment by Toldry** [comment]
For @AV306 's ease:

https://pages.github.com/

👆 follow the instructions here 👆

should only take a couple minutes

**Comment by GoulartNogueira** [comment]
Thanks for the tip!
Live demo at: https://goulartnogueira.github.io/BadUI/
