### ISSUE TITLE
Russian phone number

### ISSUE THREAD

**Issue by voronrk** [GoulartNogueira/BadUI#2]
Please add support russian phone zone (7) :)

**Comment by GoulartNogueira** [comment]
I encourage you to do it yourself by changing the:

    // Phone value is converted to a string
    function PhoneNumberToDisplay( value ) {
      // (XX)XXX-XXX-XXXX
      var display = "("+ value.toString().substr(0, 2) + ") " + value.toString().substr(2, 3) + '-' + value.toString().substr(5, 3)+'-' + value.toString().substr(8, 3);
      return display;
    }

If it has a different number of digits, you must fix it here:

     <input id="slider" type="range" min="10000000000" max="99999999999">
